version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'     # HTTP
      - '443:443'   # HTTPS
      - '81:81'     # Admin Web Port
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - payool-network
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"

volumes:
  nginx_data:
  nginx_letsencrypt:

networks:
  payool-network:
    external: true
